name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: "3.x"

      - uses: actions/checkout@v3.1.0
        with:
          submodules: "recursive"

      - name: install CI python deps
        run: pip install -r .github/requirements.txt

      - name: install repo python deps
        run: pip install -r requirements.txt

      - run: qmk setup -H $PWD -y

      - name: build keymap
        run: make moonlander:mcoding

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: moonlander_mcoding.bin
          path: .build/moonlander_mcoding.bin
          retention-days: 3
